services:
  client:
    build:
      context: .
      dockerfile: to-do-client/Dockerfile
    container_name: to-do-client
    ports:
      - "8080:80"
    restart: unless-stopped
    env_file:
      - .env

  server:
    build:
      context: .
      dockerfile: to-do-server/Dockerfile
    container_name: to-do-server
    env_file:
      - .env
    ports:
      - "3333:3333"
    restart: unless-stopped
